# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DYQ_One' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DYQ_One
pod 'AFNetworking', '~> 3.1.0'
pod 'CocoaLumberjack', '~> 2.4.0'
pod 'SDiPhoneVersion', '~> 1.1.2'
pod 'UMengAnalytics', '~> 4.1.0'
pod 'Masonry', '~> 1.0.2'
pod 'SDWebImage', '~> 3.8.2'
pod 'MJRefresh', '~> 3.1.12'
pod 'SVProgressHUD', '~> 2.0.3'

end
